### ISSUE TITLE
Where I should put the UsbDllWrap.dll?

### ISSUE THREAD

**Issue by gmezzina23** [engelsen/Instrument-control#228]
Dear sir,

I have a TLB6700. I put the UsbDllWrap.dll provided by the constructor in the current Matlab path, thus,

I tried to execute via MATLAB 2019b the following code:

`a=MyTlb6700('','3')
openDevice(a)`

since I can find "3" as the value of the USB driver in Device Management

Then I tried this:

` resp=queryCommand(a, '*IDN?');`

but the system provided me a warning: 

> "Query to Newport usb driver was unsuccessful."

Could you kindly help me?

Giovanni

**

**Comment by SAFedorov** [comment]
Hi,
UsbDllWrap.dll can be anywhere on the MATLAB path. In your case it looks like the problem is not the location of the file, UsbDllWrap is loaded in the constructor of MyNewpUsbComm and if it was not visible then the constructor would complain.

Unfortunately, the Newport driver does not seem to always behave stably, at least when used from MATLAB. In our case, when there is the problem with the driver itself, restarting the laser controller helps.

Best,
Sergey
